import { Connection, PublicKey } from '@solana/web3.js';
import { AnchorProvider, BN, Program } from '@coral-xyz/anchor';
import { W3SWAP_PROGRAM_ID, SOLANA_RPC_URL } from './constants';
import type { W3swap } from '../types/w3swap';
// IDL is generated by Anchor; JSON import enabled via resolveJsonModule
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import idl from '../idl/w3swap.json';


export enum PoolType {
  MeteoraDlmm = 0,
  OrcaWhirlpool = 1,
  RaydiumAmm = 2,
}

export interface LpConfiguration {
  poolType: PoolType;
  // Meteora DLMM specific fields
  binStep?: BN;
  activeId?: number;
  feeBps?: BN;
  activationType?: number;
  activationPoint?: BN;
  hasAlphaVault?: boolean;
  // Generic/Other fields
  initialPrice: BN;
  minPrice: BN;
  maxPrice: BN;
}


export interface CreateProjectParams {
  projectId: BN;
  projectName: string
  oldTokenMint: PublicKey;
  newTokenMint: PublicKey;
  oldTokenProgram: PublicKey;
  newTokenProgram: PublicKey;
  migrationStart: BN
  migrationEnd: BN
  exchangeRatioNumerator: BN
  exchangeRatioDenominator: BN
  solCommitmentAmount: BN
  specialRatioEnabled: boolean
  specialRatioWallets: PublicKey[]
  allowlistEnabled: boolean
  denylistEnabled: boolean
  allowlist: PublicKey[]
  denylist: PublicKey[]
}



export type Project = {
  projectId: BN;
  projectAdmin: PublicKey;
  oldTokenMint: PublicKey;
  newTokenMint: PublicKey;
  oldTokenProgram: PublicKey;
  newTokenProgram: PublicKey;
  migrationStart: BN;
  migrationEnd: BN;
  migrationDuration: BN;
  totalPauseDuration: BN;
  lastPauseStart: BN;
  activatedAt: BN;
  exchangeRatioNumerator: BN;
  exchangeRatioDenominator: BN;
  autoPauseThresholdPercent: number;
  projectName: string;
  totalOldMigrated: BN;
  totalNewDistributed: BN;
  totalSolCommitted: BN;
  lpCreated: boolean;
  lpTokensDeposited: BN;
  lpLockEnd: BN;
  meteoraPool: PublicKey;
  lpConfig: LpConfiguration | null;
  specialRatioEnabled: boolean;
  specialRatioWallets: PublicKey[];
  allowlistEnabled: boolean;
  denylistEnabled: boolean;
  allowlist: PublicKey[] | null;
  denylist: PublicKey[] | null;
  totalOldSold: BN;
  totalWsolReceived: BN;
  liquidationBackend: PublicKey | null;
  lastLiquidationSlot: BN;
  liquidationInProgress: boolean;
  bump: number;
  status: any;
}

// --- Helper Functions ---

// Initialize connection
export const getConnection = () => {
  return new Connection(SOLANA_RPC_URL, 'confirmed');
};

export const getProgram = (provider: AnchorProvider): Program<W3swap> => {
  return new Program<W3swap>(idl as W3swap, provider);
};

export function findProjectPda(programID: PublicKey, projectAdmin: PublicKey, projectId: BN): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from('project'),
      projectAdmin.toBuffer(),
      Buffer.from(new Uint8Array(new BigUint64Array([BigInt(projectId)]).buffer)),
    ],
    programID
  );
}

export function findProjectVault(seed: string, programID: PublicKey, projectPDA: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from(seed), projectPDA.toBuffer()], programID);
}

export function findPlatformConfigPda(programID: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from('platform_config')], programID);
}

// // Types for our program
// // UI-facing types used throughout the app
// export interface Project {
//   id: PublicKey; // use project PDA for unique id
//   projectId?: number;
//   projectAdmin?: string;
//   oldTokenMint: PublicKey;
//   newTokenMint: PublicKey;
//   exchangeRateOld: number;
//   exchangeRateNew: number;
//   startTime?: number;
//   endTime?: number;
//   status: string;
//   totalMigrated: number;
//   totalUsers: number;
//   createdAt: number;
//   activatedAt?: number;
// }

// export interface CreateProjectParams {
//   projectId: BN;
//   projectName: string
//   oldTokenMint: PublicKey;
//   newTokenMint: PublicKey;
//   oldTokenProgram: PublicKey;
//   newTokenProgram: PublicKey;
//   migrationStart: BN
//   migrationEnd: BN
//   exchangeRatioNumerator: BN
//   exchangeRatioDenominator: BN
//   solCommitmentAmount: BN
//   specialRatioEnabled: boolean
//   specialRatioWallets: PublicKey[]
//   allowlistEnabled: boolean
//   denylistEnabled: boolean
//   allowlist: PublicKey[]
//   denylist: PublicKey[]
// }


// export enum ProjectStatus { Created = 'Created', Active = 'Active', Completed = 'Completed', Cancelled = 'Cancelled' }
// export type UserMigration = unknown;

// // Initialize connection
// export const getConnection = () => {
//   return new Connection(SOLANA_RPC_URL, 'confirmed');
// };

// // Get program instance
// export const getProgram = (provider: AnchorProvider): Program<W3swap> => {
//   return new Program<W3swap>(idl as W3swap, provider);
// };

// // Get project PDA
// const u64LeBytes = (n: number) => {
//   const buf = Buffer.alloc(8);
//   const bn = BigInt(n);
//   buf.writeBigUInt64LE(bn);
//   return buf;
// };

// export const getProjectPDA = (projectAdmin: PublicKey, projectId: number) => {
//   return PublicKey.findProgramAddressSync(
//     [Buffer.from('project'), projectAdmin.toBuffer(), u64LeBytes(projectId)],
//     W3SWAP_PROGRAM_ID,
//   );
// };

// // Get user migration PDA
// export const getUserMigrationPDA = (user: PublicKey, project: PublicKey) => {
//   return PublicKey.findProgramAddressSync([
//     Buffer.from('user_migration'),
//     project.toBuffer(),
//     user.toBuffer(),
//   ], W3SWAP_PROGRAM_ID);
// };

// // Get liquidity vault PDA
// export const getLiquidityVaultPDA = (project: PublicKey) => {
//   return PublicKey.findProgramAddressSync([
//     Buffer.from('liquidity_vault'), project.toBuffer()
//   ], W3SWAP_PROGRAM_ID);
// };

// export const getOldTokenVaultPDA = (project: PublicKey) =>
//   PublicKey.findProgramAddressSync([Buffer.from('old_token_vault'), project.toBuffer()], W3SWAP_PROGRAM_ID);

// export const getNewTokenVaultPDA = (project: PublicKey) =>
//   PublicKey.findProgramAddressSync([Buffer.from('new_token_vault'), project.toBuffer()], W3SWAP_PROGRAM_ID);

// export const getLpEscrowVaultPDA = (project: PublicKey) =>
//   PublicKey.findProgramAddressSync([Buffer.from('lp_escrow_vault'), project.toBuffer()], W3SWAP_PROGRAM_ID);
